{% set pyproject = load_file_data('pyproject.toml') %}

package:
  name: orange-spectroscopy
  version: {{ pyproject['project']['version'] }}

source:
  git_url: ../

build:
  number: 0
  noarch: python
  script:
    - cd doc && make htmlhelp && cd ..
    - {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  build:
    - python >=3.9
    - sphinx
    - setuptools
    - recommonmark
  run:
    - python >=3.8
    - numpy >=1.24.0
    - orange3 >=3.38.0
    - orange-canvas-core >=0.2.4
    - orange-widget-base >=4.25.0
    - scipy >=1.10.0,<1.17.0
    - scikit-learn>=1.5.1
    - spectral >=0.22.3,!=0.23
    - setuptools >=51.0.0
    - pip >=19.3
    - serverfiles >=0.2
    - AnyQt >=0.2.0
    - pyqtgraph >=0.13.1
    - colorcet
    - h5py
    - extranormal3 >=0.0.3
    - renishaw_wire >=0.1.16
    - pillow >=9.2.0
    - lmfit >=1.3.3
    - bottleneck
    - pebble
    - agilent-format >=0.4.5
    - pysnom >=0.2.0
    - ptir5

test:
  imports:
    - orangecontrib.spectroscopy
  commands:
    - python -m unittest -v orangecontrib.spectroscopy.tests

about:
  home: https://github.com/quasars
  license: GPL-3
  license_family: GPL
  summary: 'Orange-Spectroscopy'

extra:
  recipe-maintainers:
    - markotoplak
